[uv sync breaks] declare that "seeds" comes from a named index
`uv sync` now throws the following error:

error: Failed to generate package metadata for `bird-feeder==1.0.0 @ editable+packages/bird-feeder`
  Caused by: Failed to parse entry for: `seeds`
  Caused by: Package is not included as workspace package in `tool.uv.workspace`